### ISSUE TITLE
Ingenico Payments with Rest, How to achieve?

### ISSUE THREAD

**Issue by SilentBackend** [Ingenico-ePayments/connect-extension-magento2#1]
Hi Team,

We are developing mobile application using Magento RestAPIs and we are in final steps, here we are integrated Ingenico As Payment.

What is the process to Integrate on mobile side. And finally what data we need to send to the following Api?

{{Host}}/rest/V1/guest-carts/{{guestCartId}}/payment-information

Can you please suggest..We are running into this problem...from last 1 week.

My thought of Payload is - {"email":"aruna.etikala@xcubelabs.com",
  "paymentMethod": {
            "method": "ingenico",
            "additional_data":{
            	"ingenico_payment_id":"3041033925_0",
            	"ingenico_payment_status":"PENDING_CAPTURE",
            	"ingenico_payment_status_code":"PENDING_CAPTURE",
            	"ingenico_payment_show_data":"welcome",
            	"ingenico_payment_product_id":1,
            	"ingenico_payment_product_label":"Visa",
            	"ingenico_payment_product_tokenize":false,
            	"ingenico_payment_product_method":"card",
            	"ingenico_payment_payload":false,
            	"ingenico_transaction_results":"",
            	"ingenico_redirect_url":"http://localhost:8070",
            	"ingenico_hosted_checkout_id":"",
            	"ingenico_returnmac":"",
            	"ingenico_idempotence_key":""
            }
   }
}

Order is creating fine...but Invoice is not generating..

Plz suggest me...

Thanks in advance...!!! Plz help me out from this problem...

**Comment by SilentBackend** [comment]
Can anyone plz help on this

**Comment by kanduvisla** [comment]
Hi @arunaetikala ,

I'm closing this issue since it looks like a Ogone call and is outdated due (2018). 

Please feel free to reopen this issue if you're still having this problem with the latest version of the module on the Ingenico Connect platform.
