### ISSUE TITLE
Quote billing and shipping address are not pre-populating after returning from hosted checkout page 

### ISSUE THREAD

**Issue by Jitheesh** [Ingenico-ePayments/connect-extension-magento2#11]
https://github.com/Ingenico-ePayments/connect-extension-magento2/blob/e0c2e89951220596712c499774cb5bb55d00ad82/Model/Cart/Service.php#L103

As you can see from above fillCartFromOrder() function, it is not copying billing and shipping address from cancelled order object to new quote object.

Is there any particular reason behind this approach ?

**Comment by Jitheesh** [comment]
@rikvanthof  Maybe using  $session->restoreQuote(); function will resolve all these issues and can remove your custom functions.

**Comment by Ingenico-Shoppingcarts-zz** [comment]
@Jitheesh Thanks for your input and it is indeed a behavior you would assume to be present. 
We made a change in Technical partner in 2019 and we have little documentation about prior choices made.

We will add it to the sprints after our next release to investigate. 
If we find no dependencies or limitations to improve the setup we will implement this. 

Please keep your feedback coming.

**Comment by Jitheesh** [comment]
Thanks.

You can also refer default Magento code with same behaviour here, hope it will helps your development. 

https://github.com/magento/magento2/blob/def8a07980c059f175cb171327ed043caf103870/app/code/Magento/Paypal/Controller/Hostedpro/Cancel.php#L48

https://github.com/magento/magento2/blob/def8a07980c059f175cb171327ed043caf103870/app/code/Magento/Paypal/Helper/Checkout.php#L50

**Comment by kanduvisla** [comment]
Hi @Jitheesh , thanks for your feedback. We've created an internal ticket for this and added it to our backlog for the next release.

**Comment by kanduvisla** [comment]
Hi @Jitheesh ,

This issue has been resolved in version `2.2.1` of the module that has just been released.
