### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by kevva** [Ingenico-ePayments/connect-extension-magento2#12]
With the introduction of an GraphQL API for Magento in version 2.3.0, there will inevitably be a growing number of users that needs support for their payment methods through GraphQL.

I'm currently working on a e-commerce site where we use your Magento extension, however I noticed there was a lack of support for GraphQL.

I was thinking of building this myself, but I thought it'd be better to open an issue here first.

Dropping this here for an example of how the Braintree implementation works https://devdocs.magento.com/guides/v2.3/graphql/payment-methods/braintree.html.

**Comment by Ingenico-Shoppingcarts-zz** [comment]
We have a regular evaluation with our partner to see what should be of high prio on the roadmap. 
Currently it is not on our roadmap for the next two releases. We strive to support the market standard and I will raise this next week. I'll be transparent on our timeline for you to be able to plan your own roadmap. I'll get back on this topic on short notice.

**Comment by kanduvisla** [comment]
Hi @kevva , we've added this to our roadmap for the next minor release. If you've (already) built something yourself (or are just willing to share) you're free to send us a pull request ;-)

**Comment by angelflo** [comment]
Hi, I'm also interested to have a GraphQl integration for Ogone payment ... let me know if someone publish this feature.

**Comment by kanduvisla** [comment]
Hi @kevva , @angelflo 

We're currently building an additional module to add GraphQl support. Would you be interested in getting a pre-release of the module to work with? Please note that this will be a `0.x`-release so it might be unstable. But this way we can get feedback in an early stage before we go for the `1.0.0`-release.

Please let me know if you're interested.

**Comment by kevva** [comment]
@kanduvisla, sorry for the absence. Yes, I'd be interested in testing this out when ready!

**Comment by kanduvisla** [comment]
Hi @kevva ,

We've just release the `0.1.0` version of the Magento 2 Connect GraphQL module: https://github.com/Ingenico-ePayments/connect-extension-magento2-graphql

Please note that according to semantic versioning, the `0.x`-version marks this repository as unstable. This does not mean that the code is a work-in-progress, but that the public API is not final and can be subject to change. Please be aware of this if you build changes on this codebase.

We're really interested in you experience with this module, so please let us know if something is not working as expected. You can do this by creating an issue in the GraphQL module.

**Comment by kevva** [comment]
@kanduvisla, I'm working on implementing this right now, but where do I send the payload? You have not added any fields onto the `PaymentMethodInput`.

**Comment by homanp** [comment]
@kanduvisla any updates on the payload for `PaymentMethodInput`?

**Comment by Ingenico-Shoppingcarts-zz** [comment]
Hi kevva and homanp, 

Kanduvisla is on leave which will delay support. We will get back with an update next week. 

kind regards,

**Comment by BarryBadpak** [comment]
Hey @kevva,  @homanp,

I'm sorry for the delay on the support request, we have investigated and as you mentioned the `PaymentMethodInput` does not have the payload specified for the payment method.

I have created an issue for this in the connect-extension-magento2-graphql repository https://github.com/Ingenico-ePayments/connect-extension-magento2-graphql/issues/2

**Comment by homanp** [comment]
Great @BarryBadpak

**Comment by kanduvisla** [comment]
This has been resolved in the latest `0.1.3` release

**Comment by angelflo** [comment]
Hi, did you plan to add full native support with ScandiPWA (perhaps already done) ?
Many magento2 extension provider now offer full integration wit their brillant PWA template.
https://marketplace.scandipwa.com/
The GraphQl implementation would proably permit to integrate it easly.

**Comment by Ingenico-Shoppingcarts** [comment]
Supporting GraphQL was the first step. 

We plan to move forward with the support of PWA in Q1 2021. 
Initially the focusing is on the native PWA studio and most likely vuestorefront.
Alternatively when you are an active merchant on our Connect API,  we can scope the required support for ScandiPWA.
