### ISSUE TITLE
Failed/Cancelled Credit Card payment still triggers order confirmation and invoice 

### ISSUE THREAD

**Issue by jochenrosen** [Ingenico-ePayments/connect-extension-magento2#13]
When I customer (logged in or guest) is not able to finish the credit card transaction and gets redirected to the Magento store the order is stored as pending but the store stills sends order confirmation transaction email and also invoice. Worked fine under Magento 2.3.3 and ingenico 3.5.2. but is not working under M 2.3.4 + I 3.5.2. No Magento backend changes have been done pre/during/post Magento upgrade.
Payment provider backend shows the transactions also as unsuccessful (code 2, 9, 46,)
Same extension works fine when used with "Sofortüberweisung" (pre and post upgrade)

The Ingenico extension in the Magento Backend is fine as it was checked a month ago by a Netresearch engineer for another reason.

**Comment by rikvanthof** [comment]
Based on the codes 2,9 and 46 you are posting I guess you are using Ingenico's Ogone Payment Platform as the backend system. This extension is meant to be used together with the Ingenico's Global Collect Payment Platform as a backend. In the past you could use the extension together with both platforms, but team working on Ingenico's Ogone Payment Platform has created new extension for use only with their platform. The latest version of the Ingenico's Ogone Payment Platform extension can be found at https://marketplace.magento.com/ingenico-m2-payment.html.

**Comment by jochenrosen** [comment]
Hi Rikvanthof, thanks for your input. On the Extension page I found "_This payment plugin should only be installed by NEW CUSTOMERS of Ingenico. If you are an existing customer, please use our deprecated plugin because the installation of our new plugin currently will not support the migration of settings and token, so it's important that existing customers only use the depreciated extension_." I am not a new customer (we came from Magento 1.8 already using the Ogone extension and migrated to 2.3.3, then 2.3.4. in Feb/April this year. What do you recommend?
thx
J

**Comment by Ingenico-Shoppingcarts-zz** [comment]
Hi, 
Your issue has been forwarded to our SMB department for further support. Feel free to reach out if you get no response in the near future. Our latest version does not allow it anymore to connect to the endpoint of SMB.

**Comment by rikvanthof** [comment]
Closing ticket, communication continued offline.
