### ISSUE TITLE
Hi need help with error in ingenico epayment module.

### ISSUE THREAD

**Issue by mishagodovanuk** [Ingenico-ePayments/connect-extension-magento2#14]
**Describe the issue**

When i try to proceed payment i get error in vendor/ingenico/library-ops-m2/Helper/Order.php on line 138
Deprecated Functionality: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior.

**Checklist**

Before posting an issue, please make sure you've checked the following checklist:
php 7.1.33
magento 2.3.4
mod:production
"ingenico/ingenico_epayments_ogn2": "^3.4",
"ingenico/library-ops-m2": "^3.5",

**To Reproduce**
Add product to cart and try to place order.
In payment method use http://joxi.ru/bmoXyMRiyNVyx2 with use this module.
Then try any operation accept/cancel etc http://joxi.ru/l2ZozWKT7DpNwA
and get this exeption

Also you can go back and get success notice massage but if you check order in admin it doesn't change.
**Expected behavior**
Payment success and order has changed status

**Comment by kanduvisla** [comment]
Hi @mishagodovanuk ,

The issue you're describing seems to be for the Ogone module. This repository is for the Ingenico Connect platform.
