### ISSUE TITLE
Magento 2.4 Support?

### ISSUE THREAD

**Issue by boehsermoe** [Ingenico-ePayments/connect-extension-magento2#15]
Does the module support magento 2.4?

**Comment by kanduvisla** [comment]
Hi @boehsermoe ,

We haven't tested the functionality of our module with Magento 2.4 yet. We're currently working towards the next minor update for the module. The compatibility check with Magento 2.4 (and possible fixes) is planned after that.

**Comment by kanduvisla** [comment]
Hi @boehsermoe , we've added support for Magento 2.4.0 in version 2.4.1 of our module.
