### ISSUE TITLE
2.4.1 release

### ISSUE THREAD

**Issue by miki-v** [Ingenico-ePayments/connect-extension-magento2#16]
Can't install a release because of the following error
  
[RuntimeException]
  Could not load package ingenico-epayments/connect-extension-magento2 in htt
  p://repo.packagist.org: [UnexpectedValueException] Could not parse version
  constraint ^4.*: Invalid version string "^4.*"

  [UnexpectedValueException]
  Could not parse version constraint ^4.*: Invalid version string "^4.*"

It works only with "symfony/console": "4.*" or "symfony/console": "^4.0" , without "^"

Could You please check this issue?

**Comment by sergiuec** [comment]
Same here, is impossible to run "composer update" for our project because of this error.
Looks like the invalid version string is on 2.1.0 tag and seems that the only solution is to remove completely that tag, but this may be done only by repo owner.

**Comment by kanduvisla** [comment]
Hi @miki-v , @sergiuec , thanks for pointing this out. Weird that an older tag of the module is currently causing this issue. I can't remember that this issue popped up during the 2.2 and 2.3-releases. Perhaps some configuration in Magento 2.4.0 is causing this behaviour. 

I'll see what I can do. Any ideas are welcome.

**Comment by sergiuec** [comment]
I have no idea what caused the issue but mine is a mage 2.3.5 project. Anyway seems that it works fine now by updating composer to latest 1.10.13 version.

P.S. thanks for your quick reply, could you please take a look at module version notification in admin, is not possible to dismiss it and it's annoying and somehow confusing to see it always. Thanks.

**Comment by kanduvisla** [comment]
@miki-v : could you also check if your problem is resolved when updating to the latest version of Composer?

**Comment by kanduvisla** [comment]
@sergiuec : could you create a new issue if you're having problems with the admin notification about the version?

**Comment by miki-v** [comment]
@kanduvisla I will check it and let you know.

**Comment by miki-v** [comment]
@kanduvisla @sergiuec  With composer 1.10.13 version the installation worked. Thank You for your response!

**Comment by frachello89** [comment]
we had the same problem in 2 projects, we solved only for one of them updating composer (from 1.10.10) to 1.10.13, in the other one problem is still present...
could you please provide a fix? removing module and repo from the composer.json do not help solving the issue.
this problem prevent to update any other module installed with composer...

**Comment by kanduvisla** [comment]
The issue is a known problem with older versions of Composer. You can also see it in the [release notes](https://github.com/composer/composer/releases/tag/1.10.13):

> Fixed regressions with old version validation

It does not only affect this project, but any composer module that at one point had an incorrect version constraint in it's `composer.json`. So I strongly suggest to update your Composer for all your projects.

We will remove the 2.1.0-tag from this repository to provide support for older versions of Composer, but since releasing to this repository is an automated process this will be done when version 2.4.2 of this module is released.

**Comment by kanduvisla** [comment]
Hi @frachello89 ,

The release and tags are now removed from this repository. Could you please confirm that this resolves the issue?
