### ISSUE TITLE
Missing transaction in magento

### ISSUE THREAD

**Issue by sergiuec** [Ingenico-ePayments/connect-extension-magento2#20]
Hello, we have an issue with some orders.
The problem is that some orders stuck in "pending" status and the transaction is missing even if in the "ingenico payment console" the order is PAID.

I tried to understand why it happens and to find something in common for all the orders but there is almost nothing that may somehow suggests what happened.

-For 2 orders I've noticed in V1 Fallback Reason the following messages: 
1. Bad Request - paymentInstrument.holder.cardHolderName must not be blank; 
2. billAddrState,shipAddrState

Apparently there are 2 different problems but as the result is the same I'll open only 1 issue report (let me know if I need to open the second issue report). I think so because:
-Some orders stuck in "pending" status and there's a message in the status history "The consumer has been redirected to a 3rd party to complete the authentication/payment. Status: REDIRECTED".
-Other orders are stuck in "pending" status without any message and are cancelled automatically in 3 days.

- How is the module configured?
  - Payment products and input fields on Hosted Checkout
  - Direct Capture
- Provide order details
  - Some are guests, some are registered customers
  - All orders are from different countries. Currency is EUR in all stores.
  - The orders are paid with 2 different card types: Visa Online(1), Mastercard Online(3)
- Platform information
  - Magento ver. 2.3.6 Commerce Cloud
  - Are you using any 3rd party modules that affect the checkout process? - NO
  - Have you written any customizations that affect the checkout process? - NO

**Comment by Ingenico-Shoppingcarts** [comment]
Thanks for the clear scenario of the issues.

Are webhooks enabled and configured ? 

To be able to troubleshoot we will have to look into the details of the transactions.
Can you send your details to Remco.vanderMeulen@ingenico.com. (MID and transaction IDs) 
I will inform your account owner and our Merchant service as soon as I receive the details on the running support.
