### ISSUE TITLE
Not redirect to HostedCheckout magento 2.4.2  Community

### ISSUE THREAD

**Issue by mesguerrae** [Ingenico-ePayments/connect-extension-magento2#21]
**Describe the issue**

Using the community version of Magento in its version 2.4.2. When trying to make a payment, the plugin does not redirect to Ingenico's Hosted checkout to make the payment.

I am currently trying to test in the pre-production environment.

When the plugin fails it generates the following log trace

_Current customer does not have an active cart.
#0 /var/www/html/lentesplus/generated/code/Magento/Quote/Model/Webapi/ParamOverriderCartId/Proxy.php(95): Magento\Quote\Model\Webapi\ParamOverriderCartId->getOverriddenValue()
#1 /var/www/html/lentesplus/app/code/Magento/Webapi/Controller/Rest/ParamsOverrider.php(64): Magento\Quote\Model\Webapi\ParamOverriderCartId\Proxy->getOverriddenValue()
#2 /var/www/html/lentesplus/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php(112): Magento\Webapi\Controller\Rest\ParamsOverrider->override()
#3 /var/www/html/lentesplus/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php(83): Magento\Webapi\Controller\Rest\InputParamsResolver->getInputData()
#4 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
#5 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callParent()
#6 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/html/lentesplus/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callPlugins()
#8 /var/www/html/lentesplus/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->resolve()
#9 /var/www/html/lentesplus/app/code/Magento/Webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#10 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#11 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#12 /var/www/html/lentesplus/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/lentesplus/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#14 /var/www/html/lentesplus/lib/internal/Magento/Framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#15 /var/www/html/lentesplus/lib/internal/Magento/Framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#16 /var/www/html/lentesplus/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#17 {main}_

**Checklist**

Before posting an issue, please make sure you've checked the following checklist:

- Are you using the latest version of the module? **2.4.6** 
- Are you using any 3rd party modules that affect the checkout process and might be causing your issue? **None**
- Have you written any customizations that affect the checkout process and might be causing your issue? **None**
- Can you reproduce the issue in Magento's default checkout module? **Yes**

**To Reproduce**

Please provide clear steps on how to reproduce the behavior. Also provide the following information:

- How is the module configured?
  - What checkout type are you using? (Hosted? Inline? Payment products in Magento checkout, input fields on Hosted Checkout?) **Hosted**
  - What capture mode are you using? (Delayed settlement? Direct capture?) **Direct**
- Provide order details
  - Is it a guest checkout or a registered customer? **Register customer**
  - What's the country & currency? **Colombia - COP**
  - What is the selected payment product?
- Platform information
  - What is the Magento version you're using?- **2.4.2 Community**
  - Are you using any 3rd party modules that affect the checkout process? **None**
  - Have you written any customizations that affect the checkout process? **None**

**Expected behavior**

Redirect to checkout to make payment

**Comment by Ingenico-Shoppingcarts** [comment]
@mesguerrae My apologies for the late reply. 

We will release 2.5.X version of the Module, planned for this week.
Validated if there are any issues with Magento 2.4.2 and the hosted checkout. 
In the error shared from Magento the first feedback of the developer was the absence of a reference to our module.  

Moving forward, we will pick up the communication on the issue. I will reach out to my Colleague to get all the contact details. 

The issue of a missing CartID is only in relation to Ingenico, the native check money order works fine and disabling the module of Ingenico allows you to process steps in the checkout without any error ?

**Comment by mesguerrae** [comment]
@Ingenico-Shoppingcarts thanks for the answer me.

It is correct, **_this error only occurs with Ingenico's payment method_**, other payment methods work correctly and do not present the error allowing the purchase to be completed.

**Comment by bertterheide** [comment]
@mesguerrae does this issue also occur in the latest version of this module?
