### ISSUE TITLE
Error update Language Pack in Ingenico Language Packe editor

### ISSUE THREAD

**Issue by mesguerrae** [Ingenico-ePayments/connect-extension-magento2#22]
**Describe the issue**

When a change is made to the language pack, is it necessary to carry out some other process or wait a certain time?, Since a change was made but it does not update:

**Checklist**

Before posting an issue, please make sure you've checked the following checklist:

1.	Download the pack
2.	Make the changes
3.	Upload the pack on a new Locale name
4.	Make sure you refer in your API call to this new Locale name

**To Reproduce**

In Language pack editor:

1.	Download the pack
2.	Make the changes
3.	Upload the pack on a new Locale name
4.	Make sure you refer in your API call to this new Locale name

![1](https://user-images.githubusercontent.com/37119650/134693559-51d26d3c-a82a-4f08-972b-46df62aa9b43.png)
![2](https://user-images.githubusercontent.com/37119650/134693562-bfcb0a2c-0d03-4374-ac48-44ed9088be78.png)
![3](https://user-images.githubusercontent.com/37119650/134693564-fbeb3ef8-b5d4-4014-8b5a-bb3621e57efa.jpg)
![4](https://user-images.githubusercontent.com/37119650/134693566-456840c8-ca1c-468c-9e40-9c86f0e46c33.jpg)
![5](https://user-images.githubusercontent.com/37119650/134693571-0a362a60-7182-4d1a-9ef9-1302dd6b6a5b.jpg)
![6](https://user-images.githubusercontent.com/37119650/134693574-491b3e8e-59f4-458b-98c8-3be603813ab7.jpg)

**Comment by Ingenico-Shoppingcarts** [comment]
@mesguerrae The screen shared are related to the layer of Worldline and are not related to the language packs of Magento. 
If you have issues with the changes committed in the Configuration Center please reach out to our Merchant Services. Contact details are displayed in the Support tab part of the settings in Magento. 

Feel free to commit a new comment if you are still stuck with the changes.
