### ISSUE TITLE
Error in redirection to show payment methods

### ISSUE THREAD

**Issue by mesguerrae** [Ingenico-ePayments/connect-extension-magento2#23]
**Describe the issue**

When we select payment with Ingenico and it redirects to Hosted Checkout, it does not show card options either for debiting bank accounts but instead tries to make payment directly by debiting the bank account

But with the same parameters and the same version of the plugin in another environment it works

Configuration is replicated to try to replicate the error but in another environment if it works, will it be some plugin error?

Images of success and error environment configuration are attached, and videos of evidence of the two environments

**Checklist**

- Plugin configuration
- Plugin version
- 

**To Reproduce**

We were unable to reproduce the cause

**Expected behavior**

That allows you to select the payment methods enabled

Success Config

![Success Enviroment config](https://user-images.githubusercontent.com/37119650/159818554-243762ec-5b46-4e3c-b8ee-4706b91fe15f.png)

Success Flow

https://user-images.githubusercontent.com/37119650/159818563-c431693b-95a4-4fea-9f74-ef91367f3870.mp4

Error Flow 

https://user-images.githubusercontent.com/37119650/159818559-22735420-af3a-43af-afdc-133c8f513027.mp4

Error config

![Error Enviroment config](https://user-images.githubusercontent.com/37119650/159818561-5760d807-d390-4836-ab9d-fb4ef5d47f44.png)

**Comment by mesguerrae** [comment]
We have managed to reproduce the error and it turns out that if you sent a large value, either in the price of the product or in the value of the shipment (speaking of millions of Colombian pesos), it fails. Fails when the order total as greater than 5000 EUR

Big Shipping Value

![Big Shipping value 1](https://user-images.githubusercontent.com/37119650/159932045-c7aa7c32-4a99-43b4-94ef-5080c4a15868.png)
![Big Shipping value 2](https://user-images.githubusercontent.com/37119650/159932068-40cea28b-ceed-41d8-b603-85cbd712f14f.png)

Big Product Price
![Big product price (1)](https://user-images.githubusercontent.com/37119650/159932301-d1479fab-57e7-4597-b00c-7bf37d070418.png)

![Big product price (2)](https://user-images.githubusercontent.com/37119650/159932305-415cde43-b1f1-4151-8827-f95dd740f6e4.png)

In our trade these values are possible in a sale

**Comment by kpaluskar** [comment]
Thank you for explaining it in details and apologies for delay in the response. If you're an existing customer then Please reach out to your account manager/implementation team to increase the maximum transaction limit. If you're a prospective customer then it is not possible to change the account limit on sandbox. On production, it will be configured as per your need.
