### ISSUE TITLE
Error: "Could not establish connection to Worldline Connect platform" in production mode - PHP 8.1

### ISSUE THREAD

**Issue by sergiuec** [Ingenico-ePayments/connect-extension-magento2#29]
Hello,
There is a deprecated function in sdk.  It's reproducible only in production mode.

`report.EMERGENCY: Unable to perform request using communicator configuration: Deprecated Functionality: curl_multi_exec(): Passing null to parameter #2 ($still_running) of type int is deprecated in /vendor/ingenico-epayments/connect-sdk-php/lib/Ingenico/Connect/Sdk/DefaultConnection.php on line 206 [] []`

Fixed by defining the `$runing` variable before passing it to `curl_multi_exec`

`@@ -202,6 +202,7 @@
     private function executeCurlHandleShared($multiHandle, $curlHandle)
     {
          $running = 0;`

PHP 8.1.17
Module Version: 3.0.2
Magento Version: Commerce Cloud 2.4.5-p2

**Comment by bertterheide** [comment]
@sergiuec which version of the SDK are you using? This should be fixed in 6.36.0 and you should be able to upgrade to that version without problems.

**Comment by sergiuec** [comment]
Looks like the version is: 6.38.0
composer.lock:
```
"name": "ingenico-epayments/connect-sdk-php",
"version": "6.38.0"
```

the command: `composer update ingenico-epayments/connect-sdk-php` returns "Nothing to install, update or remove"

In case may be useful this is the source from composer.lock:
```
"source": {
    "type": "git",
    "url": "https://github.com/Ingenico-ePayments/connect-sdk-php.git",
    "reference": "xx"
},
```

**Comment by bertterheide** [comment]
@sergiuec thanks. I’ll inform the team that develops the SDK.

**Comment by bertterheide** [comment]
@sergiuec since this should be fixed in the SDK I'm going to close this issue. Is that okay with you?

**Comment by rob-spoor** [comment]
Release [6.38.2](https://github.com/Ingenico-ePayments/connect-sdk-php/releases/tag/6.38.2) of the SDK should fix this issue.
